"""Codegen: embed the exact extracted HLSL into a C++ header for the native renderer.
Re-run if native_renderer/shaders/*.hlsl change. Output is committed.
"""
from pathlib import Path
root = Path(__file__).resolve().parent
vert = (root / "shaders" / "yuv_framepack.vert.hlsl").read_text(encoding="utf-8")
frag = (root / "shaders" / "yuv_framepack.frag.hlsl").read_text(encoding="utf-8")
delim = "SYLCHLSL"
for name, src in (("vert", vert), ("frag", frag)):
    if f'){delim}"' in src:
        raise SystemExit(f"raw-string delimiter collision in {name}")


def emit_literal(src, chunk=8000):
    """Embed `src` as one or more ADJACENT raw-string literals (C++ concatenates them).
    A single MSVC narrow string literal is capped at ~16 KB (error C2026), so the shader
    is split into <=`chunk`-byte pieces. The literal tokens are separated by whitespace
    only, so the concatenated content is byte-identical to `"\\n" + src + "\\n"` — exactly
    what the previous single-literal form embedded."""
    body = "\n" + src + "\n"
    parts = [body[i:i + chunk] for i in range(0, len(body), chunk)] or [""]
    return "\n".join(f'R"{delim}({p}){delim}"' for p in parts)


out = root.parent / "mvc_realtime_demuxer" / "src" / "native_renderer_shaders.h"
text = f'''// AUTO-GENERATED by native_renderer/gen_shader_header.py — do not edit by hand.
// Exact HLSL SM5.0 extracted from the baked yuv_framepack .qsb (byte-for-byte the
// shader the Qt RHI renderer uses). Entry point "main" for both stages.
// Each shader is emitted as ADJACENT raw-string literals (concatenated by the compiler)
// to stay under MSVC's ~16 KB per-string-literal limit (C2026).
#pragma once
#ifdef SYLC_NATIVE_RENDERER
namespace sylc {{

inline const char* kVertexHLSL =
{emit_literal(vert)};

inline const char* kFragmentHLSL =
{emit_literal(frag)};

}} // namespace sylc
#endif // SYLC_NATIVE_RENDERER
'''
out.write_text(text, encoding="utf-8")
print(f"wrote {out} ({len(text)} bytes; vert={len(vert)}, frag={len(frag)})")
