"""Codegen: embed the exact extracted HLSL into a C++ header for the native renderer.
Re-run if native_renderer/shaders/*.hlsl change. Output is committed.
"""
from pathlib import Path
root = Path(__file__).resolve().parent
vert = (root / "shaders" / "yuv_framepack.vert.hlsl").read_text(encoding="utf-8")
frag = (root / "shaders" / "yuv_framepack.frag.hlsl").read_text(encoding="utf-8")
delim = "SYLCHLSL"
for name, src in (("vert", vert), ("frag", frag)):
    if f'){delim}"' in src:
        raise SystemExit(f"raw-string delimiter collision in {name}")
out = root.parent / "mvc_realtime_demuxer" / "src" / "native_renderer_shaders.h"
text = f'''// AUTO-GENERATED by native_renderer/gen_shader_header.py — do not edit by hand.
// Exact HLSL SM5.0 extracted from the baked yuv_framepack .qsb (byte-for-byte the
// shader the Qt RHI renderer uses). Entry point "main" for both stages.
#pragma once
#ifdef SYLC_NATIVE_RENDERER
namespace sylc {{

inline const char* kVertexHLSL = R"{delim}(
{vert}
){delim}";

inline const char* kFragmentHLSL = R"{delim}(
{frag}
){delim}";

}} // namespace sylc
#endif // SYLC_NATIVE_RENDERER
'''
out.write_text(text, encoding="utf-8")
print(f"wrote {out} ({len(text)} bytes; vert={len(vert)}, frag={len(frag)})")
