// AUTO-GENERATED by native_renderer/gen_shader_header.py — do not edit by hand.
// Exact HLSL SM5.0 extracted from the baked yuv_framepack .qsb (byte-for-byte the
// shader the Qt RHI renderer uses). Entry point "main" for both stages.
#pragma once
#ifdef SYLC_NATIVE_RENDERER
namespace sylc {

inline const char* kVertexHLSL = R"SYLCHLSL(
static float4 gl_Position;
static float2 v_texCoord;
static float2 texCoord;
static float2 position;

struct SPIRV_Cross_Input
{
    float2 position : TEXCOORD0;
    float2 texCoord : TEXCOORD1;
};

struct SPIRV_Cross_Output
{
    float2 v_texCoord : TEXCOORD0;
    float4 gl_Position : SV_Position;
};

void vert_main()
{
    v_texCoord = texCoord;
    gl_Position = float4(position, 0.0f, 1.0f);
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    texCoord = stage_input.texCoord;
    position = stage_input.position;
    vert_main();
    SPIRV_Cross_Output stage_output;
    stage_output.gl_Position = gl_Position;
    stage_output.v_texCoord = v_texCoord;
    return stage_output;
}

)SYLCHLSL";

inline const char* kFragmentHLSL = R"SYLCHLSL(
static const float _182[6] = { -2.5f, -1.5f, -0.5f, 0.5f, 1.5f, 2.5f };

cbuffer buf : register(b0)
{
    int _401_stereo_mode : packoffset(c0);
    int _401_subtitle_enabled : packoffset(c0.y);
    float4 _401_subtitle_rect : packoffset(c1);
    float _401_sdr_white_level : packoffset(c2);
    float _401_output_gamma : packoffset(c2.y);
    float _401_fp_vfill : packoffset(c2.z);
    float _401_fp_hfill : packoffset(c2.w);
};

Texture2D<float4> texSubtitle : register(t0);
SamplerState _texSubtitle_sampler : register(s0);
Texture2D<float4> texY_L : register(t1);
SamplerState _texY_L_sampler : register(s1);
Texture2D<float4> texU_L : register(t2);
SamplerState _texU_L_sampler : register(s2);
Texture2D<float4> texV_L : register(t3);
SamplerState _texV_L_sampler : register(s3);
Texture2D<float4> texY_R : register(t4);
SamplerState _texY_R_sampler : register(s4);
Texture2D<float4> texU_R : register(t5);
SamplerState _texU_R_sampler : register(s5);
Texture2D<float4> texV_R : register(t6);
SamplerState _texV_R_sampler : register(s6);

static float2 v_texCoord;
static float4 fragColor;

struct SPIRV_Cross_Input
{
    float2 v_texCoord : TEXCOORD0;
};

struct SPIRV_Cross_Output
{
    float4 fragColor : SV_Target0;
};

float3 YUVtoRGB(inout float y, inout float u, inout float v)
{
    y = (y - 0.062745101749897003173828125f) * 1.16438353061676025390625f;
    u -= 0.5f;
    v -= 0.5f;
    float r = y + (1.401999950408935546875f * v);
    float g = (y - (0.3441359996795654296875f * u)) - (0.71413600444793701171875f * v);
    float b = y + (1.77199995517730712890625f * u);
    return clamp(float3(r, g, b), 0.0f.xxx, 1.0f.xxx);
}

float3 sampleYUV(Texture2D<float4> texY, SamplerState _texY_sampler, Texture2D<float4> texU, SamplerState _texU_sampler, Texture2D<float4> texV, SamplerState _texV_sampler, inout float2 uv)
{
    uv = clamp(uv, 0.001000000047497451305389404296875f.xx, 0.999000012874603271484375f.xx);
    float y = texY.Sample(_texY_sampler, uv).x;
    float u = texU.Sample(_texU_sampler, uv).x;
    float v = texV.Sample(_texV_sampler, uv).x;
    float param = y;
    float param_1 = u;
    float param_2 = v;
    float3 _396 = YUVtoRGB(param, param_1, param_2);
    return _396;
}

float spline36(inout float x)
{
    x = abs(x);
    if (x < 1.0f)
    {
        return (((((1.18181812763214111328125f * x) - 2.1674640178680419921875f) * x) - 0.01435406692326068878173828125f) * x) + 1.0f;
    }
    else
    {
        if (x < 2.0f)
        {
            float t = x - 1.0f;
            return (((((-0.545454561710357666015625f) * t) + 1.2918660640716552734375f) * t) - 0.746411502361297607421875f) * t;
        }
        else
        {
            if (x < 3.0f)
            {
                float t_1 = x - 2.0f;
                return ((((0.0909090936183929443359375f * t_1) - 0.21531100571155548095703125f) * t_1) + 0.12440191209316253662109375f) * t_1;
            }
        }
    }
    return 0.0f;
}

float3 sampleYUV_Spline36_H(Texture2D<float4> texY, SamplerState _texY_sampler, Texture2D<float4> texU, SamplerState _texU_sampler, Texture2D<float4> texV, SamplerState _texV_sampler, float2 uv)
{
    float pixelW = 0.0005208333604969084262847900390625f;
    float srcX = uv.x * 1920.0f;
    float centerX = srcX;
    float sumY = 0.0f;
    float sumU = 0.0f;
    float sumV = 0.0f;
    float sumW = 0.0f;
    for (int i = 0; i < 6; i++)
    {
        float offset = _182[i];
        float param = offset;
        float _206 = spline36(param);
        float weight = _206;
        float sampleX = (centerX + offset) * pixelW;
        sampleX = clamp(sampleX, 0.001000000047497451305389404296875f, 0.999000012874603271484375f);
        float2 sampleUV = float2(sampleX, clamp(uv.y, 0.001000000047497451305389404296875f, 0.999000012874603271484375f));
        sumY += (texY.Sample(_texY_sampler, sampleUV).x * weight);
        sumU += (texU.Sample(_texU_sampler, sampleUV).x * weight);
        sumV += (texV.Sample(_texV_sampler, sampleUV).x * weight);
        sumW += weight;
    }
    if (sumW > 0.0f)
    {
        sumY /= sumW;
        sumU /= sumW;
        sumV /= sumW;
    }
    float param_1 = sumY;
    float param_2 = sumU;
    float param_3 = sumV;
    float3 _273 = YUVtoRGB(param_1, param_2, param_3);
    return _273;
}

float3 sampleYUV_Spline36_V(Texture2D<float4> texY, SamplerState _texY_sampler, Texture2D<float4> texU, SamplerState _texU_sampler, Texture2D<float4> texV, SamplerState _texV_sampler, float2 uv)
{
    float pixelH = 0.000925925909541547298431396484375f;
    float srcY = uv.y * 1080.0f;
    float centerY = srcY;
    float sumY = 0.0f;
    float sumU = 0.0f;
    float sumV = 0.0f;
    float sumW = 0.0f;
    for (int i = 0; i < 6; i++)
    {
        float offset = _182[i];
        float param = offset;
        float _305 = spline36(param);
        float weight = _305;
        float sampleY = (centerY + offset) * pixelH;
        sampleY = clamp(sampleY, 0.001000000047497451305389404296875f, 0.999000012874603271484375f);
        float2 sampleUV = float2(clamp(uv.x, 0.001000000047497451305389404296875f, 0.999000012874603271484375f), sampleY);
        sumY += (texY.Sample(_texY_sampler, sampleUV).x * weight);
        sumU += (texU.Sample(_texU_sampler, sampleUV).x * weight);
        sumV += (texV.Sample(_texV_sampler, sampleUV).x * weight);
        sumW += weight;
    }
    if (sumW > 0.0f)
    {
        sumY /= sumW;
        sumU /= sumW;
        sumV /= sumW;
    }
    float param_1 = sumY;
    float param_2 = sumU;
    float param_3 = sumV;
    float3 _368 = YUVtoRGB(param_1, param_2, param_3);
    return _368;
}

float4 sampleSubtitle(float2 videoUV)
{
    if (_401_subtitle_enabled == 0)
    {
        return 0.0f.xxxx;
    }
    float sx = _401_subtitle_rect.x;
    float sy = _401_subtitle_rect.y;
    float sw = _401_subtitle_rect.z;
    float sh = _401_subtitle_rect.w;
    bool _429 = videoUV.x >= sx;
    bool _438;
    if (_429)
    {
        _438 = videoUV.x < (sx + sw);
    }
    else
    {
        _438 = _429;
    }
    bool _445;
    if (_438)
    {
        _445 = videoUV.y >= sy;
    }
    else
    {
        _445 = _438;
    }
    bool _454;
    if (_445)
    {
        _454 = videoUV.y < (sy + sh);
    }
    else
    {
        _454 = _445;
    }
    if (_454)
    {
        float2 subUV = float2((videoUV.x - sx) / sw, (videoUV.y - sy) / sh);
        return texSubtitle.Sample(_texSubtitle_sampler, subUV);
    }
    return 0.0f.xxxx;
}

float3 blendSubtitle(float3 videoRGB, float4 subtitleRGBA)
{
    return lerp(videoRGB, subtitleRGBA.xyz, subtitleRGBA.w.xxx);
}

void frag_main()
{
    float y_flipped = 1.0f - v_texCoord.y;
    float3 rgb;
    float2 videoUV;
    if (_401_stereo_mode == 0)
    {
        float2 uv = float2(v_texCoord.x, y_flipped);
        float2 param = uv;
        float3 _510 = sampleYUV(texY_L, _texY_L_sampler, texU_L, _texU_L_sampler, texV_L, _texV_L_sampler, param);
        rgb = _510;
        videoUV = uv;
    }
    else
    {
        if (_401_stereo_mode == 1)
        {
            // FramePack: top eye + 45px gap + bottom eye. Each eye is letterboxed
            // into its 1080-tall slot using fp_vfill/fp_hfill (derived from the source
            // aspect) so a non-16:9 eye (e.g. Full-SBS 1920x1012) keeps its native
            // resolution with black bars instead of a vertical stretch. A 16:9 eye
            // (MVC) has fp_vfill=fp_hfill=1 and fills the slot exactly (unchanged).
            float vbar = (1.0f - _401_fp_vfill) * 0.5f;
            float hbar = (1.0f - _401_fp_hfill) * 0.5f;
            if (y_flipped < 0.4897958934307098388671875f)
            {
                float ly = y_flipped / 0.4897958934307098388671875f;
                if (ly < vbar || ly > (1.0f - vbar) || v_texCoord.x < hbar || v_texCoord.x > (1.0f - hbar))
                {
                    rgb = 0.0f.xxx;
                    videoUV = (-1.0f).xx;
                }
                else
                {
                    float2 uv_1 = float2((v_texCoord.x - hbar) / _401_fp_hfill, (ly - vbar) / _401_fp_vfill);
                    float2 param_1 = uv_1;
                    rgb = sampleYUV(texY_L, _texY_L_sampler, texU_L, _texU_L_sampler, texV_L, _texV_L_sampler, param_1);
                    videoUV = uv_1;
                }
            }
            else
            {
                if (y_flipped > 0.5102040767669677734375f)
                {
                    float ly2 = (y_flipped - 0.5102040767669677734375f) / 0.4897958934307098388671875f;
                    if (ly2 < vbar || ly2 > (1.0f - vbar) || v_texCoord.x < hbar || v_texCoord.x > (1.0f - hbar))
                    {
                        rgb = 0.0f.xxx;
                        videoUV = (-1.0f).xx;
                    }
                    else
                    {
                        float2 uv_2 = float2((v_texCoord.x - hbar) / _401_fp_hfill, (ly2 - vbar) / _401_fp_vfill);
                        float2 param_2 = uv_2;
                        rgb = sampleYUV(texY_R, _texY_R_sampler, texU_R, _texU_R_sampler, texV_R, _texV_R_sampler, param_2);
                        videoUV = uv_2;
                    }
                }
                else
                {
                    rgb = 0.0f.xxx;
                    videoUV = (-1.0f).xx;
                }
            }
        }
        else
        {
            if (_401_stereo_mode == 2)
            {
                if (v_texCoord.x < 0.5f)
                {
                    float2 uv_3 = float2(v_texCoord.x * 2.0f, y_flipped);
                    float2 param_3 = uv_3;
                    rgb = sampleYUV_Spline36_H(texY_L, _texY_L_sampler, texU_L, _texU_L_sampler, texV_L, _texV_L_sampler, param_3);
                    videoUV = uv_3;
                }
                else
                {
                    float2 uv_4 = float2((v_texCoord.x - 0.5f) * 2.0f, y_flipped);
                    float2 param_4 = uv_4;
                    rgb = sampleYUV_Spline36_H(texY_R, _texY_R_sampler, texU_R, _texU_R_sampler, texV_R, _texV_R_sampler, param_4);
                    videoUV = uv_4;
                }
            }
            else
            {
                if (_401_stereo_mode == 3)
                {
                    if (y_flipped < 0.5f)
                    {
                        float2 uv_5 = float2(v_texCoord.x, y_flipped * 2.0f);
                        float2 param_5 = uv_5;
                        rgb = sampleYUV_Spline36_V(texY_L, _texY_L_sampler, texU_L, _texU_L_sampler, texV_L, _texV_L_sampler, param_5);
                        videoUV = uv_5;
                    }
                    else
                    {
                        float2 uv_6 = float2(v_texCoord.x, (y_flipped - 0.5f) * 2.0f);
                        float2 param_6 = uv_6;
                        rgb = sampleYUV_Spline36_V(texY_R, _texY_R_sampler, texU_R, _texU_R_sampler, texV_R, _texV_R_sampler, param_6);
                        videoUV = uv_6;
                    }
                }
            }
        }
    }
    float2 param_7 = videoUV;
    float4 subtitle = sampleSubtitle(param_7);
    float3 param_8 = rgb;
    float4 param_9 = subtitle;
    rgb = blendSubtitle(param_8, param_9);
    // Optional EOTF: linearize the gamma-domain RGB before scaling into the
    // (linear) scRGB FP16 buffer. output_gamma <= 0 disables it (raw passthrough).
    if (_401_output_gamma > 0.0f) { rgb = pow(max(rgb, 0.0f.xxx), _401_output_gamma.xxx); }
    rgb *= _401_sdr_white_level;
    fragColor = float4(rgb, 1.0f);
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    v_texCoord = stage_input.v_texCoord;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.fragColor = fragColor;
    return stage_output;
}

)SYLCHLSL";

} // namespace sylc
#endif // SYLC_NATIVE_RENDERER
