// AUTO-GENERATED by native_renderer/gen_shader_header.py — do not edit by hand.
// Source of truth: mvc_realtime_demuxer/shaders/yuv_to_nv12_sbs.hlsl (re-run the
// generator if it changes). ONE HLSL source with three entry points (VS, PS_Luma,
// PS_Chroma); sbs_nv12_packer.cpp compiles this single constant once per entry point.
// Emitted as ADJACENT raw-string literals to stay under MSVC's ~16 KB per-literal
// limit (C2026).
#pragma once
#ifdef SYLC_NATIVE_RENDERER
namespace sylc {

inline const char* kSbsPackHLSL =
R"SYLCHLSL(
// yuv_to_nv12_sbs.hlsl — VS = fullscreen triangle; two pixel shaders.
// Luma pass -> R8 target (3840x1080). Chroma pass -> R8G8 target (1920x540, interleaved U,V).
//
// Subtitle burn-in (SyLC Cast): the display shader composites the RGBA subtitle
// overlay AFTER YUV->RGB, so the packed NV12 the cast encodes never carried it.
// Both passes therefore blend the SAME overlay here, in YUV space. This is
// mathematically identical to the display's RGB lerp: Y'CbCr is an AFFINE map of
// R'G'B', and affine maps commute with lerp — so converting the subtitle texel to
// YUV once and lerping per component equals converting the blended RGB result.
// The conversion is the EXACT inverse of the display shader's BT.709-limited
// branch, so a burned subtitle round-trips to the same RGB the local display
// composites (and 1080p receivers decode with BT.709 anyway).
Texture2D<float> LY:register(t0); Texture2D<float> LU:register(t1); Texture2D<float> LV:register(t2);
Texture2D<float> RY:register(t3); Texture2D<float> RU:register(t4); Texture2D<float> RV:register(t5);
Texture2D<float4> SUB:register(t6);          // RGBA8 straight-alpha subtitle overlay
SamplerState smp:register(s0);               // POINT sampling — no interpolation (lossless video)
SamplerState subSmp:register(s1);            // LINEAR — the overlay scales to eye space

cbuffer SubCB : register(b0) {
    int    sub_enabled;      // c0.x  0 = burn nothing (both passes reduce to the lossless copy)
    float  sub_disparity;    // c0.y  normalized eye width; > 0 = pop-out (crossed)
    float  plane_scale;      // c0.z  per-sample scale before writing: 1.0 for 8-bit R8
                             //       planes AND HW P010 R16 planes (both are already
                             //       target-normalized); 65535/1023 ~= 64.06 rescales a
                             //       SW-decoded 10-bit value stored low in R16 up to the
                             //       P010 MSB alignment the 10-bit output plane expects.
    float  _pad;             // c0.w
    float4 sub_rect;         // c1    normalized (x, y, w, h) in per-eye space
};

struct VSOut { float4 pos:SV_Position; float2 uv:TEXCOORD0; };
VSOut VS(uint id:SV_VertexID) {
    VSOut o; float2 t = float2((id<<1)&2, id&2);   // (0,0)(2,0)(0,2) fullscreen triangle
    o.uv = t; o.pos = float4(t*float2(2,-2)+float2(-1,1), 0, 1); return o;
}

// Subtitle RGBA at per-eye coord e. eyeSign: +1 = left eye, -1 = right eye.
// Same convention as the display shader's sampleSubtitle: each eye is shifted
// by HALF the disparity, in opposite directions; shifting the displayed overlay
// by +s means sampling the rect at (x - s).
float4 sampleSub(float2 e, float eyeSign) {
    if (sub_enabled == 0) return 0.0.xxxx;
    float x = e.x - eyeSign * sub_disparity * 0.5;
    if (x < sub_rect.x || x >= sub_rect.x + sub_rect.z ||
        e.y < sub_rect.y || e.y >= sub_rect.y + sub_rect.w) return 0.0.xxxx;
    float2 suv = float2((x - sub_rect.x) / sub_rect.z, (e.y - sub_rect.y) / sub_rect.w);
    return SUB.SampleLevel(subSmp, suv, 0);
}

// EXACT inverse of the display shader's BT.709-limited YUVtoRGB branch:
//   y = (Y - 16/255) * 1.16438...; r = y + 1.5748 v; g = y - .18732 u - .46812 v;
//   b = y + 1.8556 u   (u, v centered on 0.5, NOT 224-range rescaled).
float3 rgbToYuv709(float3 rgb) {
    float y = dot(rgb, float3(0.2126, 0.7152, 0.0722));
    float u = (rgb.b - y) / 1.8556;
    float v = (rgb.r - y) / 1.5748;
    return float3(y / 1.16438353061676025390625 + 0.062745101749897,
                  u + 0.5, v + 0.5);
}

float PS_Luma(VSOut i):SV_Target {
    bool right = i.uv.x >= 0.5;
    float2 e = float2(right ? (i.uv.x-0.5)*2.0 : i.uv.x*2.0, i.uv.y);
    float y = (right ? RY.SampleLevel(smp,e,0) : LY.SampleLevel(smp,e,0)) * plane_scale;
    float4 s = sampleSub(e, right ? -1.0 : 1.0);
    if (s.a > 0.0) y = lerp(y, rgbToYuv709(s.rgb).x, s.a);
    return y;
}
float2 PS_Chroma(VSOut i):SV_Target {          // R8G8 (NV12) or R16G16 (P010) output = (U,V)
    bool right = i.uv.x >= 0.5;
    float2 e = float2(right ? (i.uv.x-0.5)*2.0 : i.uv.x*2.0, i.uv.y);
    float u = (right ? RU.SampleLevel(smp,e,0) : LU.SampleLevel(smp,e,0)) * plane_scale;
    float v = (right ? RV.SampleLevel(smp,e,0) : LV.SampleLevel(smp,e,0)) * plane_scale;
    float4 s = sampleSub(e, right ? -1.0 : 1.0);
    if (s.a > 0.0) {
        float3 syuv = rgbToYuv709(s.rgb);
        u = lerp(u, syuv.y, s.a);
        v = lerp(v, syuv.z, s.a);
    }
    return float2(u, v);
}

)SYLCHLSL";

} // namespace sylc
#endif // SYLC_NATIVE_RENDERER
